### ISSUE TITLE
Web Interface "Internal Server Error", Log permission denied status 113

### ISSUE THREAD

**Issue by fightforlife** [OpenMediaVault-Plugin-Developers/openmediavault-cups#10]
fresh simplenas image on a Banana Pi. (wheezy)
Everything wirks and is updated, omv2.2.4

Installing this plugin works and it shows in the sidebar. But I cant access any tabs in the CUPS webinterface or add a printer over omv.
Example Error-log for the admin page:
​D [22/May/2016:21:54:16 +0200] [CGI] Started /usr/lib/cups/cgi-bin/admin.cgi (PID 10550)
I [22/May/2016:21:54:16 +0200] Started "/usr/lib/cups/cgi-bin/admin.cgi" (pid=10550)
D [22/May/2016:21:54:16 +0200] cupsdSendCommand: 14 file=15
D [22/May/2016:21:54:16 +0200] PID 10550 (/usr/lib/cups/cgi-bin/admin.cgi) stopped with status 113 (Permission denied)
D [22/May/2016:21:54:16 +0200] cupsdWriteClient: 14 Closing because Keep-Alive disabled

It seems there is a permission issue.
CUPsd is started as root, most cups files are 755 and owned by root, root is member of the lpadmin group.

If i change the permissions to 777, the web interface says "not found" and the log tells me that the permissions are unseure...

I can reproduce it everytime.

**Comment by nohatssir** [comment]
You need to tell us how you can reproduce it because from my testing I can't find any issue.

**Comment by fightforlife** [comment]
1. Fresh installation of simplesNas image: http://simplenas.com/download/banana-pi-m1
(which is wheezy with omv, used it long time before without problems.)
2. apt-get upgrade, verifiying everything works.
3. installing cups pugin, activating plugin. Always the same permission error on Cups Webend

Which permissions should this file have?
/usr/lib/cups/cgi-bin/admin.cgi

All other plugins and functions are working just fine....

**Comment by nohatssir** [comment]
It at least works on an amd64 system. From what I gather that sounds more like a cups package problem than a bug in the plugin. The correct permissions are that the file is owned by root and has 755 permissions.

@ryecoaaron I don't own a Banana Pi so I can't reproduce it, maybe you've got any ideas?

**Comment by ryecoaaron** [comment]
I would agree that this is a package issue with the BPi.  I don't own one either but we have a lot of issues with the BPi.  Pretty sure this doesn't happen on the RPi so I rule out the plugin and arm architectures as the issue.

**Comment by fightforlife** [comment]
Thank you very much for your answers, i tried to reach the developer of the bpi image, but so far no answer,
I will probably try a standard debian wheezy image without omv. If CUPS works there I know its an image problem. If it doesnt it is a cups package problem. 
I will let you know, thanks again.

**Comment by nohatssir** [comment]
There's nothing we can do if we can't reproduce it. I'm not much for pure guessing.
