### ISSUE TITLE
IOS 7 Support

### ISSUE THREAD

**Issue by ZiroNL** [OpenMediaVault-Plugin-Developers/openmediavault-cups#3]
The Airprint config needs some changes to work with IOS7, maybe it could be implemented?
I got mine setup working now, but it would be nice if it works out of the box.

/usr/share/cups/mime/airprint.types:
image/urf urf (0,UNIRAST)

/usr/share/cups/mime/local.convs:
image/urf application/vnd.cups-postscript 66 pdftops

/etc/cups/cupsd.conf:
"ServerAlias *" needs to be changed to the hostname of OMV (nas.local for example)

/etc/avahi/services/omvcups-Airprint-<printer name>.servcice:
Add "image/urf" to the pdl string.

**Comment by nohatssir** [comment]
Is this still an issue and if that's the casse, does anyone have a patch for it?
