### ISSUE TITLE
impliment xsane to scan over network

### ISSUE THREAD

**Issue by happyreacer** [OpenMediaVault-Plugin-Developers/openmediavault-cups#7]
Can we implament xsane for scanning over network form a "all in one" printer in the Cups Plugin or in a New one?
seem like thees: http://forums.openmediavault.org/index.php/Thread/415-How-to-get-a-scanner-to-work-with-OMV-Network-Scanner/
or see
http://forums.openmediavault.org/index.php/Thread/8508-What-is-the-best-way-to-share-a-scanner-on-the-network/?s=7c581494e951efb8c97744b1cb5f81432c102cb5

**Comment by nohatssir** [comment]
This could probably be implemented in another plugin by someone who wants to do it. The two shouldn't be combined into one plugin though since they're two different things.
