### ISSUE TITLE
CUPS fails to install on OMV 2.1

### ISSUE THREAD

**Issue by nakwada** [OpenMediaVault-Plugin-Developers/openmediavault-cups#8]
Hello,

Havin' trouble making CUPS plugin work on my fresh OMV 2.1 install.

Log here :

Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  openmediavault-cups
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/44.4 kB of archives.
After this operation, 280 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openmediavault-cups
Authentication warning overridden.
Selecting previously unselected package openmediavault-cups.
(Reading database ... 39235 files and directories currently installed.)
Unpacking openmediavault-cups (from .../openmediavault-cups_1.0.9_all.deb) ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Setting up openmediavault-cups (1.0.9) ...
Restarting Common Unix Printing System: cupsd.
Requirement already satisfied (use --upgrade to upgrade): cloudprint in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Downloading/unpacking pycups (from cloudprint)
  Running setup.py egg_info for package pycups
    
Installing collected packages: pycups
  Running setup.py install for pycups
    building 'cups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt:
    running install

running build

running build_ext

building 'cups' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o

unable to execute gcc: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt failed with error code 1 in /build/pycups
Storing complete log in /root/.pip/pip.log
dpkg: error processing openmediavault-cups (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for openmediavault ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-cups

>>> *************** Error ***************
Failed to execute command 'export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-cups 2>&1': Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  openmediavault-cups
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/44.4 kB of archives.
After this operation, 280 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openmediavault-cups
Authentication warning overridden.
Selecting previously unselected package openmediavault-cups.
(Reading database ...
39235 files and directories currently installed.)
Unpacking openmediavault-cups (from .../openmediavault-cups_1.0.9_all.deb) ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Setting up openmediavault-cups (1.0.9) ...
Restarting Common Unix Printing System: cupsd
.
Requirement already satisfied (use --upgrade to upgrade): cloudprint in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Downloading/unpacking pycups (from cloudprint)
  Running setup.py egg_info for package pycups

Installing collected packages: pycups
  Running setup.py install for pycups
    building 'cups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt:
    running install

running build

running build_ext

building 'cups' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o

unable to execute gcc: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt failed with error code 1 in /build/pycups
Storing complete log in /root/.pip/pip.log
dpkg: error processing openmediavault-cups (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for openmediavault ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-cups
Creating index of upgradeable packages ...
Creating index of OpenMediaVault plugins ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-cups 2>&1': Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  openmediavault-cups
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/44.4 kB of archives.
After this operation, 280 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openmediavault-cups
Authentication warning overridden.
Selecting previously unselected package openmediavault-cups.
(Reading database ...
39235 files and directories currently installed.)
Unpacking openmediavault-cups (from .../openmediavault-cups_1.0.9_all.deb) ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Setting up openmediavault-cups (1.0.9) ...
Restarting Common Unix Printing System: cupsd
.
Requirement already satisfied (use --upgrade to upgrade): cloudprint in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Downloading/unpacking pycups (from cloudprint)
  Running setup.py egg_info for package pycups

Installing collected packages: pycups
  Running setup.py install for pycups
    building 'cups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt:
    running install

running build

running build_ext

building 'cups' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o

unable to execute gcc: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt failed with error code 1 in /build/pycups
Storing complete log in /root/.pip/pip.log
dpkg: error processing openmediavault-cups (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for openmediavault ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-cups
Creating index of upgradeable packages ...
Creating index of OpenMediaVault plugins ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-cups 2>&1': Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  openmediavault-cups
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/44.4 kB of archives.
After this operation, 280 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openmediavault-cups
Authentication warning overridden.
Selecting previously unselected package openmediavault-cups.
(Reading database ...
39235 files and directories currently installed.)
Unpacking openmediavault-cups (from .../openmediavault-cups_1.0.9_all.deb) ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Setting up openmediavault-cups (1.0.9) ...
Restarting Common Unix Printing System: cupsd
.
Requirement already satisfied (use --upgrade to upgrade): cloudprint in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Downloading/unpacking pycups (from cloudprint)
  Running setup.py egg_info for package pycups

Installing collected packages: pycups
  Running setup.py install for pycups
    building 'cups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt:
    running install

running build

running build_ext

building 'cups' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o

unable to execute gcc: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt failed with error code 1 in /build/pycups
Storing complete log in /root/.pip/pip.log
dpkg: error processing openmediavault-cups (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for openmediavault ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-cups
Creating index of upgradeable packages ...
Creating index of OpenMediaVault plugins ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-cups 2>&1': Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  openmediavault-cups
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/44.4 kB of archives.
After this operation, 280 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openmediavault-cups
Authentication warning overridden.
Selecting previously unselected package openmediavault-cups.
(Reading database ...
39235 files and directories currently installed.)
Unpacking openmediavault-cups (from .../openmediavault-cups_1.0.9_all.deb) ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Setting up openmediavault-cups (1.0.9) ...
Restarting Common Unix Printing System: cupsd
.
Requirement already satisfied (use --upgrade to upgrade): cloudprint in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Downloading/unpacking pycups (from cloudprint)
  Running setup.py egg_info for package pycups

Installing collected packages: pycups
  Running setup.py install for pycups
    building 'cups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt:
    running install

running build

running build_ext

building 'cups' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o

unable to execute gcc: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt failed with error code 1 in /build/pycups
Storing complete log in /root/.pip/pip.log
dpkg: error processing openmediavault-cups (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for openmediavault ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-cups
Creating index of upgradeable packages ...
Creating index of OpenMediaVault plugins ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
<<< *************************************

>>> *************** Error ***************
Failed to execute command 'export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-cups 2>&1': Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  openmediavault-cups
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/44.4 kB of archives.
After this operation, 280 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openmediavault-cups
Authentication warning overridden.
Selecting previously unselected package openmediavault-cups.
(Reading database ...
39235 files and directories currently installed.)
Unpacking openmediavault-cups (from .../openmediavault-cups_1.0.9_all.deb) ...
Processing triggers for openmediavault ...
Restarting engine daemon ...
Setting up openmediavault-cups (1.0.9) ...
Restarting Common Unix Printing System: cupsd
.
Requirement already satisfied (use --upgrade to upgrade): cloudprint in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from cloudprint)
Downloading/unpacking pycups (from cloudprint)
  Running setup.py egg_info for package pycups

Installing collected packages: pycups
  Running setup.py install for pycups
    building 'cups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt:
    running install

running build

running build_ext

building 'cups' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o

unable to execute gcc: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/build/pycups/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-z0JKLV-record/install-record.txt failed with error code 1 in /build/pycups
Storing complete log in /root/.pip/pip.log
dpkg: error processing openmediavault-cups (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for openmediavault ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-cups
Creating index of upgradeable packages ...
Creating index of OpenMediaVault plugins ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
<<< *************************************

**Comment by nohatssir** [comment]
gcc seems to be missing when building some package with pip install. In versions after 1.0.9 the use of python-pip to install stuff is dropped so the issue should be solved with that. Until the next version is released you could install the build-essential package and try again.

**Comment by nakwada** [comment]
Hello nohatssir and thank you for your fast reply !

Installing the buil-essential pack solved only part of the problem.
I also had to install python-dev and libcups2-dev to make it work.
Then I reinstalled cups plugin flawlessly :)

Cheers
